# Generated by Django 2.2.3 on 2019-08-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default='images/default_cover.png', null=True, upload_to='playlist_cover/', verbose_name='커버이미지'),
        ),
    ]
