# Generated by Django 2.2.3 on 2019-08-09 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='likes',
        ),
        migrations.AddField(
            model_name='playlist',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_users', through='playlists.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
