# Generated by Django 2.2.3 on 2019-07-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성된 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 시간')),
                ('title', models.CharField(max_length=200, verbose_name='글제목')),
                ('genre', models.CharField(max_length=200, verbose_name='장르')),
                ('singer', models.CharField(max_length=200, verbose_name='가수')),
                ('lyrics', models.TextField(blank=True, verbose_name='가사')),
                ('link', models.TextField(blank=True, verbose_name='링크')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '노래',
                'verbose_name_plural': '노래',
            },
        ),
    ]
